---
- name: ensure python3-pip is installed on debian-based distros
  ansible.builtin.apt:
    name: python3-pip
  when: ansible_os_family == "Debian"
- name: install ansible with pip on debian-based distros
  ansible.builtin.pip:
    name: ansible
  when: ansible_os_family == "Debian"
- name: ensure ansible is installed on arch linux
  community.general.pacman:
    name: ansible
    update_cache: yes
  when: ansible_os_family == 'Archlinux'
- name: run setup.yml via ansible-pull
  ansible.builtin.command: ansible-pull -U https://github.com/heywoodlh/ansible setup.yml
- name: run playbooks/servers/server.yml via ansible-pull
  ansible.builtin.command: ansible-pull -U https://github.com/heywoodlh/ansible playbooks/servers/server.yml
