---
- name: list current tailscale machines
  ansible.builtin.command: tailscale status --json | jq '.Peer | to_entries[] | select(.value.Tags[] | contains("tag:server") or contains("tag:gaming")) | .value'
  register: tailscale_json
- name: parse the json of tailscale output
  ansible.builtin.set_fact:
    parsed_json: "{{ tailscale_json.stdout | b64decode | from_json }}"
- name: perform actions on each host
  block:
  - name: Set facts for item
    set_fact:
      ip_addr: "{{ item.TailscaleIPs.split(',')[0] }}"
      hostname: "{{ item.HostName }}"
      operating_system: "{{ item.OS }}" 
  loop: "{{ parsed_items }}"
