---
- name: create send-docker redis directory
  file:
    path: "{{ send_root_dir }}/redis/"
    mode: 0700
    owner: "{{ container_uid }}"
    state: directory
  become: true
- name: deploy redis docker container
  docker_container:
    name: "send_redis"
    image: redis
    restart_policy: unless-stopped
    user: "{{ container_uid }}"
    volumes:
    - "{{ send_root_dir }}/redis:/data"
  become: true
