---
- name: "create bibliogram directories in {{ bibliogram_root_dir }}"
  file:
    path: "{{ item }}"
    state: directory
    force: no
    owner: "{{ bibliogram_uuid }}"
    group: "{{ bibliogram_guid }}"
    recurse: yes
  with_items:
  - "{{ bibliogram_db_dir }}"
  become: true
- name: "git clone https://git.sr.ht/~cadence/bibliogram {{ bibliogram_git_dir }}"
  git:
    repo: https://git.sr.ht/~cadence/bibliogram
    dest: "{{ bibliogram_git_dir }}"
    force: yes
- name: build local bibliogram image
  docker_image:
    name: local/bibliogram
    tag: latest
    path: "{{ bibliogram_git_dir }}"
    state: present
  become: true
- name: run bibliogram container
  docker_container:
    name: bibliogram
    image: local/bibliogram
    restart_policy: unless-stopped
    volumes:
    - "{{ bibliogram_db_dir }}:/app/db"
    ports:
    - "{{ bibliogram_http_port }}:10407"
  become: true
