---
- hosts: all
  become: true
  tasks:
  - name: run security playbooks
    ansible.builtin.import_playbook: security/*.yml
  - name: run users playbooks
    ansible.builtin.import_playbook: users/*.yml
