---
- hosts: localhost
  vars_files:
  - vars/main.yml
  become: true
  roles:
  - role: pkgs
    when: ansible_os_distribution == "Debian" or ansible_os_distribution == "Archlinux"
  - role: updates
    when: ansible_os_distribution == "Debian" or ansible_os_distribution == "Archlinux"
  - role: security
    when: ansible_os_distribution == "Debian" or ansible_os_distribution == "Archlinux"
  - role: users
    when: ansible_os_distribution == "Debian" or ansible_os_distribution == "Archlinux"
  - role: tarsnap
    when: ansible_os_distribution == "Debian" or ansible_os_distribution == "Archlinux"
  - role: proxmox
    when: ansible_os_distribution == "Debian" or ansible_os_distribution == "Archlinux"
  - role: systemd
    when: ansible_os_distribution == "Debian" or ansible_os_distribution == "Archlinux"
  - role: ad-hoc
    when: ansible_os_distribution == "Debian" or ansible_os_distribution == "Archlinux"
  - role: nixos
    when: ansible_os_distribution == "NixOS"
