---
- hosts: localhost
  become: true
  tasks:
  - name: run security playbooks
    ansible.builtin.import_playbook: "playbooks/servers/security/{{ item }}"
    with_items:
    - sshd-alert.yml
  #- name: run users playbooks
    #ansible.builtin.import_playbook: "users/heywoodlh.yml"
