---
- hosts: localhost
  vars_files:
  - vars/main.yml
  become: true
  roles:
  - role: pkgs
  - role: updates
  - role: security
  - role: users
  - role: tarsnap
  - role: proxmox
  - role: ad-hoc
