---
- hosts: all
  become: true
  tasks:
  - name: run security playbooks
    ansible.builtin.import_playbook: "security/{{ items }}"
    with_items:
    - sshd-alert.yml
  - name: run users playbooks
    ansible.builtin.import_playbook: users/*.yml
