---
- name: create heywoodlh
  ansible.builtin.user:
    name: heywoodlh
- name: passwordless sudo for heywoodlh
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/heywoodlh
    state: present
    create: yes
    regexp: "^heywoodlh"
    line: "heywoodlh ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
- name: create heywoodlh .ssh directory
  ansible.builtin.file:
    path: /home/heywoodlh/.ssh
    mode: '0700'
    owner: heywoodlh
    state: directory
- name: grab authorized_keys file
  ansible.builtin.copy:
    src: authorized_keys
    dest: /home/heywoodlh/.ssh/authorized_keys
    mode: '0600'
    owner: heywoodlh
