---
- name: create heywoodlh
  ansible.builtin.user:
    name: heywoodlh
- name: passwordless sudo for heywoodlh
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/heywoodlh
    state: present
    create: yes
    regexp: "^heywoodlh"
    line: "heywoodlh ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
- name: remove sudo configuration from archinstall script if exists
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: "^heywoodlh"
    line: "heywoodlh ALL=(ALL) ALL"
    validate: 'visudo -cf %s'
- name: create heywoodlh .ssh directory
  ansible.builtin.file:
    path: /home/heywoodlh/.ssh
    mode: '0700'
    owner: heywoodlh
    state: directory
- name: grab authorized_keys file
  ansible.builtin.copy:
    src: authorized_keys
    dest: /home/heywoodlh/.ssh/authorized_keys
    mode: '0600'
    owner: heywoodlh
- name: install nix in single-user mode
  ansible.builtin.shell: curl -L https://nixos.org/nix/install | sh -s -- --no-daemon --yes
  become_user: heywoodlh
  when: nix_check.stat.exists == false
- name: install my nixos-configs server flake
  ansible.builtin.command: "/home/heywoodlh/.nix-profile/bin/nix --extra-experimental-features 'nix-command flakes' run github:heywoodlh/nixos-configs#homeConfigurations.heywoodlh-server.activationPackage --impure"
  become: yes
  become_user: heywoodlh
- name: add /home/heywoodlh/.nix-profile/bin/zsh to /etc/shells
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "/home/heywoodlh/.nix-profile/bin/zsh"
- name: set heywoodlh's shell to /home/heywoodlh/.nix-profile/bin/zsh
  ansible.builtin.user:
    name: heywoodlh
    shell: /home/heywoodlh/.nix-profile/bin/zsh
- name: create /home/heywoodlh/.zsh.d
  ansible.builtin.file:
    state: directory
    create: true
    mode: '0700'
    owner: heywoodlh
- name: add ansible-switch alias to /home/heywoodlh/.zsh.d/custom
  ansible.builtin.lineinfile:
    path: /home/heywoodlh/.zsh.d/custom
    line: "alias ansible-switch='sudo ansible-pull -U https://github.com/heywoodlh/ansible setup.yml; sudo ansible-pull -U https://github.com/heywoodlh/ansible playbooks/servers/server.yml'"
    create: yes
    owner: heywoodlh
