---
- name: remove nagios-monitor user
  ansible.builtin.user:
    name: nagios-monitor
    state: absent
- name: remove nagios-monitor user home directory
  ansible.builtin.file:
    path: /home/nagios-monitor
    state: absent
- name: create nagios
  ansible.builtin.user:
    name: nagios
- name: create nagios .ssh directory
  ansible.builtin.file:
    path: /home/nagios/.ssh
    mode: '0700'
    owner: nagios
    state: directory
- name: grab authorized_keys file
  ansible.builtin.copy:
    src: nagios_authorized_keys
    dest: /home/nagios/.ssh/authorized_keys
    mode: '0600'
    owner: nagios
