---
- name: create nagios-monitor
  ansible.builtin.user:
    name: nagios-monitor
- name: create nagios-monitor .ssh directory
  ansible.builtin.file:
    path: /home/nagios-monitor/.ssh
    mode: '0700'
    owner: nagios-monitor
    state: directory
- name: grab authorized_keys file
  ansible.builtin.copy:
    src: nagios-monitor_authorized_keys
    dest: /home/nagios-monitor/.ssh/authorized_keys
    mode: '0600'
    owner: nagios-monitor
