---
- name: "create synapse directories in {{ synapse_root_dir }}"
  file:
    path: "{{ item }}"
    state: directory
    force: no
    owner: "{{ synapse_uuid }}"
    group: "{{ synapse_guid }}"
    recurse: yes
  with_items: "{{ synapse_dirs }}"
  become: true
- name: "pull {{ synapse_image }}:{{ synapse_version }} image"
  docker_image:
    name: "{{ synapse_image }}"
    tag: "{{ synapse_version }}"
    source: pull
  become: true
- name: generate initial synapse config
  docker_container:
    name: synapse
    image: "{{ synapse_image }}:{{ synapse_version }}"
    auto_remove: yes
    volumes: "{{ synapse_volumes }}"
    env: "{{ synapse_env }}"
    command: generate
  become: true
- name: run synapse container
  docker_container:
    name: synapse
    image: "{{ synapse_image }}:{{ synapse_version }}"
    restart_policy: unless-stopped
    volumes: "{{ synapse_volumes }}"
    env: "{{ synapse_env }}"
    ports: "{{ synapse_ports }}"
    command: start
  become: true
