---
- name: "create synapse directories in {{ synapse_root_dir }}"
  file:
    path: "{{ item }}"
    state: directory
    force: no
    owner: "{{ synapse_uuid }}"
    group: "{{ synapse_guid }}"
    recurse: yes
  with_items: "{{ synapse_dirs }}"
  become: true
- name: "pull {{ synapse_image }}:{{ synapse_version }} image"
  docker_image:
    name: "{{ synapse_image }}"
    tag: "{{ synapse_version }}"
    source: pull
  become: true
- name: "copy base config to {{ synapse_data_dir }}/homeserver.yaml"
  template:
    src: homeserver.yaml.j2
    dest: "{{ synapse_data_dir }}/homeserver.yaml"
    owner: "{{ synapse_uuid }}"
    group: "{{ synapse_guid }}"
    force: no
    mode: 0600
  become: true
- name: run synapse container
  docker_container:
    name: synapse
    image: "{{ synapse_image }}:{{ synapse_version }}"
    restart_policy: unless-stopped
    volumes: "{{ synapse_volumes }}"
    env: "{{ synapse_env }}"
    ports:
      "{{ synapse_port }}:8008"
  become: true
