---
- name: "create {{ radicale_root_dir }}"
  file:
    path: "{{ radicale_root_dir }}"
    state: directory
    force: no
- name: "create {{ radicale_data_dir }}"
  file:
    path: "{{ radicale_data_dir }}"
    state: directory
- name: "copy config to {{ radicale_root_dir }}"
  copy:
    src: config
    dest: "{{ radicale_root_dir}}/config"
- name: "pull tomsquest/docker-radicale image"
  docker_image:
    name: tomsquest/docker-radicale
    source: pull
- name: run radicale container
  docker_container:
    name: radicale
    image: "tomsquest/docker-radicale"
    restart_policy: unless-stopped
    volumes: "{{ radicale_volumes }}"
    ports: "{{ radicale_ports }}"
    capabilities:
    - SYS_ADMIN
    - CHOWN
    - SETUID
    - SETGID
    - KILL
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5232"]
      interval: 30s
      retries: 3
