image: debian
packages:
  - git
  - python3
  - python3-pip
sources:
  - https://git.sr.ht/~heywoodlh/ansible
tasks:
  - setup: |
      pip3 install ansible
      cd ansible
      ansible-playbook setup.yml
      cd playbooks/servers
      ansible-playbook server.yml \
        && ls -l /usr/local/bin/gotify
triggers:
  - action: email
    condition: failure
    to: heywoodlh@tyrannyofthesun.com
