image: debian/stable
packages:
  - git
  - python3
  - python3-pip
tasks:
  - setup: |
      sudo pip3 install ansible
      sudo ansible-pull -U 'https://github.com/heywoodlh/ansible' setup.yml
      sudo ansible-pull -U 'https://github.com/heywoodlh/ansible' playbooks/servers/server.yml \
        && ls -l /usr/local/bin/gotify
triggers:
  - action: email
    condition: failure
    to: heywoodlh@tyrannyofthesun.com
