---
- hosts: all
  become: true
  tasks:
  - name: import user vars
    ansible.builtin.include_vars:
      file: vars/users.yml
  - name: "passwordless sudo for {{ ssh_user }}"
    ansible.builtin.lineinfile:
      path: "/etc/sudoers.d/{{ ssh_user }}"
      state: present
      regexp: "^{{ ssh_user }}"
      line: "{{ ssh_user }} ALL=(ALL) NOPASSWD: ALL"
      validate: 'visudo -cf %s'
  - name: grab authorized_keys file
    ansible.builtin.get_url:
      url: "{{ authorized_keys_uri }}"
      dest: "/home/{{ ssh_user }}/.ssh/authorized_keys"
      mode: '0600'
      owner: "{{ ssh_user }}"
