---
- name: check if /etc/pve directory exists
  stat:
    path: /etc/pve
  register: pve-check 
- name: removes subscription nag box
  include: remove-nag.yml
  when: pve-check.stat.exists and remove_nag
- name: remove enterprise repo
  include: remove-enterprise-repo.yml
  when: pve-check.stat.exists and remove_enterprise_repo
- name: add no subcription repo
  include: add-no-subscription-repo.yml
  when: pve-check.stat.exists and add_no_subscription_repo
