---
- name: update cache (so we don't have to for each package that gets installed)
  ansible.builtin.apt:
    update_cache: yes
- name: install global packages
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items: "{{ global_packages }}"
- name: install debian-specific packages
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items: "{{ debian_packages }}"
