---
- name: create heywoodlh (don't set shell until home-manager is setup)
  ansible.builtin.user:
    name: heywoodlh
- name: add heywoodlh to nix-users on arch 
  ansible.builtin.user:
    name: heywoodlh
    append: true
    groups: nix-users
  when: ansible_os_family == 'Archlinux'
- name: remove sudo configuration from archinstall script if exists
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: "^heywoodlh"
    line: "heywoodlh ALL=(ALL) ALL"
    validate: 'visudo -cf %s'
- name: sudo configuration from archinstall script if exists
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/heywoodlh
    line: "heywoodlh ALL=(ALL) ALL"
    validate: 'visudo -cf %s'
    create: yes
- name: check if /nix exists
  ansible.builtin.stat:
    path: /nix
  register: nix_check
- name: install nix in single-user mode
  ansible.builtin.shell: curl -L https://nixos.org/nix/install | sh -s -- --no-daemon --yes
  become_user: heywoodlh
  when: nix_check.stat.exists == false
- name: install nixos-configs
  ansible.builtin.shell: |
    source /home/heywoodlh/.nix-profile/etc/profile.d/nix.sh
    nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
    nix-channel --update
    if [[ ! -e /home/heywoodlh/.nix-profile/bin/home-manager ]]
    then
      nix-shell '<home-manager>' -A install
    fi
    source /home/heywoodlh/.nix-profile/etc/profile.d/hm-session-vars.sh
    export NIX_CONFIG="experimental-features = nix-command flakes"
    /home/heywoodlh/.nix-profile/bin/home-manager --flake github:heywoodlh/nixos-configs#heywoodlh-desktop-$(arch) -b bak switch
  args:
    executable: /bin/bash
  become_user: heywoodlh
  ignore_errors: true
- name: add /home/heywoodlh/.nix-profile/bin/zsh to /etc/shells
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "/home/heywoodlh/.nix-profile/bin/zsh"
- name: check if /home/heywoodlh/.nix-profile/bin/zsh exists
  ansible.builtin.stat:
    path: /home/heywoodlh/.nix-profile/bin/zsh
  register: nix_zsh
- name: set heywoodlh's shell to /home/heywoodlh/.nix-profile/bin/zsh
  ansible.builtin.user:
    name: heywoodlh
    shell: /home/heywoodlh/.nix-profile/bin/zsh
  when: nix_zsh.stat.exists
- name: create /home/heywoodlh/.zsh.d
  ansible.builtin.file:
    path: /home/heywoodlh/.zsh.d
    state: directory
    mode: '0700' 
    owner: heywoodlh
- name: add ansible-switch alias to /home/heywoodlh/.zsh.d/custom
  ansible.builtin.lineinfile:
    path: /home/heywoodlh/.zsh.d/custom
    line: "alias ansible-switch='sudo ansible-pull -U https://github.com/heywoodlh/ansible setup.yml; sudo ansible-pull -U https://github.com/heywoodlh/ansible playbooks/workstation/workstation.yml'"
    create: true
    owner: heywoodlh
