---
- name: create heywoodlh (don't set shell until home-manager is setup)
  ansible.builtin.user:
    name: heywoodlh
- name: remove sudo configuration from archinstall script if exists
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: "^heywoodlh"
    line: "heywoodlh ALL=(ALL) ALL"
    validate: 'visudo -cf %s'
- name: sudo configuration from archinstall script if exists
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/heywoodlh
    line: "heywoodlh ALL=(ALL) ALL"
    validate: 'visudo -cf %s'
    create: yes
- name: create nix-profile heywoodlh folder
  ansible.builtin.file:
    path: /nix/var/nix/profiles/per-user/heywoodlh
    owner: heywoodlh
    state: directory
    mode: 755
- name: install my nixos-configs flake
  ansible.builtin.command: "/nix/var/nix/profiles/default/bin/nix --extra-experimental-features 'nix-command flakes' run github:heywoodlh/nixos-configs#homeConfigurations.heywoodlh-desktop-{{ ansible_architecture }}.activationPackage --impure --out-link ~/.nix-profile"
  become: yes
  become_user: heywoodlh
- name: add /home/heywoodlh/.nix-profile/bin/zsh to /etc/shells
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "/home/heywoodlh/.nix-profile/bin/zsh"
- name: set heywoodlh's shell to /home/heywoodlh/.nix-profile/bin/zsh
  ansible.builtin.user:
    name: heywoodlh
    shell: /home/heywoodlh/.nix-profile/bin/zsh
- name: create /home/heywoodlh/.zsh.d
  ansible.builtin.file:
    state: directory
    create: true
    mode: '0700' 
    owner: heywoodlh
- name: add ansible-switch alias to /home/heywoodlh/.zsh.d/custom
  ansible.builtin.lineinfile:
    path: /home/heywoodlh/.zsh.d/custom
    line: "alias ansible-switch='sudo ansible-pull -U https://github.com/heywoodlh/ansible setup.yml; sudo ansible-pull -U https://github.com/heywoodlh/ansible playbooks/workstations/workstation.yml'"
    create: yes
    owner: heywoodlh
