---
- name: passwordless sudo for heywoodlh
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/heywoodlh
    state: present
    create: yes
    regexp: "^heywoodlh"
    line: "heywoodlh ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
- name: remove sudo configuration from archinstall script if exists
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: "^heywoodlh"
    line: "heywoodlh ALL=(ALL) ALL"
    validate: 'visudo -cf %s'
- name: copy brew-install.sh
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh 
    dest: /tmp/brew-install.sh
    mode: +x
- name: install homebrew (will complete after 30 seconds)
  ansible.builtin.script: /tmp/brew-install.sh 
  timeout: 60
  become: yes
  become_user: heywoodlh
  environment:
    NONINTERACTIVE: 1
  ignore_errors: yes
- name: check if homebrew exists
  ansible.builtin.stat:
    path: /home/linuxbrew/.linuxbrew/bin/brew 
  register: brew_bin
- name: fail if homebrew does not exist
  ansible.builtin.fail:
    msg: Homebrew is still not installed
  when: not brew_bin.stat.exists
- name: update homebrew core
  ansible.builtin.command: git -C /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core pull --depth=1 
  become: yes
  become_user: heywoodlh
- name: remove passwordless sudo for heywoodlh
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/heywoodlh
    state: present
    create: yes
    regexp: "^heywoodlh"
    line: "heywoodlh ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
- name: add sudo configuration for heywoodlh 
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: "^heywoodlh"
    line: "heywoodlh ALL=(ALL) ALL"
    validate: 'visudo -cf %s'
- name: source homebrew globally 
  ansible.builtin.lineinfile:
    path: /etc/profile
    line: 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' 
- name: disable homebrew analytics
  ansible.builtin.lineinfile:
    path: /etc/profile
    line: "export HOMEBREW_NO_ANALYTICS=1"
