---
- name: update cache and archlinux-keyring before moving to other packages
  community.general.pacman:
    name: archlinux-keyring
    update_cache: yes
  when: ansible_os_family == 'Archlinux' 
- name: install arch packages
  community.general.pacman:
    name: "{{ item }}"
  with_items:
  - cronie
  - git
  - gcc
  - glibc
  - make
  - wget
  - dnsutils
  - unzip
  - traceroute
  when: ansible_os_family == 'Archlinux' 
- name: enable cronie service
  ansible.builtin.systemd:
    name: cronie.service
    enabled: yes
    state: started
  when: ansible_os_family == 'Archlinux'
- name: update apt cache
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_os_family == 'Debian'
- name: install debian packages
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items:
  - git
  - autoconf
  - gcc
  - libc6
  - libmcrypt-dev
  - make
  - libssl-dev
  - wget
  - bc
  - gawk
  - dc
  - build-essential
  - snmp
  - libnet-snmp-perl
  - gettext
  when: ansible_os_family == 'Debian'

