---
- name: install arch packages
  community.general.pacman:
    name: "{{ item }}"
  with_items:
  - cronie
- name: enable cronie service
  ansible.builtin.systemd:
    name: cronie.service
    enabled: yes
    state: started
  
