---
- name: arch linux mirrorlist repo configuration
  ansible.builtin.copy:
    src: mirrorlist
    path: /etc/pacman.d/mirrorlist
    backup: true
    owner: root
    mode: 644
  when: ansible_distribution == 'Archlinux'
