---
- name: install syslog-ng 
  community.general.pacman:
    name: "{{ item }}"
  with_items:
  - syslog-ng
  when: ansible_os_family == 'Archlinux' 
- name: install syslog-ng 
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items:
  - syslog-ng
  when: ansible_os_family == 'Debian'
- name: create syslog-ng conf.d
  ansible.builtin.file:
    path: /etc/syslog-ng/conf.d/
    state: directory
- name: configure syslog-ng to use /etc/syslog-ng/conf.d
  ansible.builtin.copy:
    src: syslog-ng/syslog-ng.conf
    dest: /etc/syslog-ng/syslog-ng.conf
    force: yes
- name: configure syslog-ng conf.d
  ansible.builtin.copy:
    src: syslog-ng/conf.d/*.conf
    dest: /etc/syslog-ng/conf.d
    force: yes
  register: conf_d
- name: increase max open file count
  ansible.posix.sysctl:
    name: fs.file-max
    value: '500000'
    reload: yes
- name: start and enable syslog-ng
  ansible.builtin.systemd:
    name: syslog-ng.service
    enabled: true
    state: started
  when: ansible_os_family == 'Debian'
- name: start and enable syslog-ng
  ansible.builtin.systemd:
    name: syslog-ng@default.service
    enabled: true
    state: started 
  when: ansible_os_family == 'Archlinux'
- name: restart syslog-ng if changes to /etc/syslog-ng/conf.d were detected
  ansible.builtin.systemd:
    name: syslog-ng.service
    state: restarted
  when: ansible_os_family == 'Debian' and conf_d.changed
- name: restart syslog-ng if changes to /etc/syslog-ng/conf.d were detected
  ansible.builtin.systemd:
    name: syslog-ng@default.service
    state: restarted 
  when: ansible_os_family == 'Archlinux' and conf_d.changed

