---
- name: check if config exists
  stat:
    path: "{{ znc_data_dir }}/configs/znc.conf"
  register: file
  become: true
- name: "create znc directories in {{ znc_root_dir }}"
  file:
    path: "{{ item }}"
    state: directory
    force: no
    owner: "{{ znc_uuid }}"
    group: "{{ znc_guid }}"
    recurse: yes
  with_items:
  - "{{ znc_data_dir }}/configs"
  become: true
- name: "pull znc:{{ znc_version }} image"
  docker_image:
    name: znc
    tag: "{{ znc_version }}"
    source: pull
  become: true
- name: "copy initial configuration if {{ znc_data_dir }}/config/znc.conf didn't exist before"
  template:
    src: znc.conf.j2
    dest: "{{ znc_data_dir }}/config/znc.conf"
    owner: "{{ znc_uuid }}"
    group: "{{ znc_guid }}"
    mode: 0640
  when: file.stat.exists == False
  become: true
- name: run znc container
  docker_container:
    name: znc
    image: "znc:{{ znc_version }}"
    restart_policy: unless-stopped
    volumes: "{{ znc_volumes }}"
    ports: "{{ znc_ports }}"
  become: true
