---
nfs_root_dir: "/home/heywoodlh/core/nfs"
nfs_data_dir: "{{ nfs_root_dir }}/data"
nfs_uuid: "1000"
nfs_guid: "1000"
nfs_port: "2049"
nfs_volumes:
- "{{ nfs_data_dir }}/public:/nfs_share/public"
- "{{ nfs_root_dir }}/exports:/etc/exports:ro" 
- /etc/timezone:/etc/timezone:ro
- /etc/localtime:/etc/localtime:ro
nfs_version: "latest"
