---
- name: "create {{ jenkins_root_dir }}"
  file:
    path: "{{ jenkins_root_dir }}"
    state: directory
    force: no
- name: "pull {{ jenkins_image }}:{{ jenkins_image_version }} image"
  community.docker.docker_image:
    name: "{{ jenkins_image }}"
    tag: "{{ jenkins_image_version }}"
    source: pull
- name: run jenkins container
  community.docker.docker_container:
    name: jenkins
    image: "{{ jenkins_image }}:{{ jenkins_image_version }}"
    restart_policy: unless-stopped
    volumes: "{{ jenkins_volumes }}"
    ports: "{{ jenkins_ports }}"
    env: "{{ jenkins_env }}"
