---
- name: "create tinytinyrss directories in {{ tinytinyrss_root_dir }}"
  file:
    path: "{{ item }}"
    state: directory
    force: no
    owner: "{{ tinytinyrss_uuid }}"
    group: "{{ tinytinyrss_guid }}"
    recurse: yes
  with_items:
  - "{{ tinytinyrss_data_dir }}"
  - "{{ tinytinyrss_db_dir }}"
  become: true
- name: "git clone https://git.tt-rss.org/fox/ttrss-docker-compose {{ tinytinyrss_git_dir }}"
  git:
    repo: "https://git.tt-rss.org/fox/ttrss-docker-compose"
    dest: "{{ tinytinyrss_git_dir }}"
    force: yes
  become: true
- name: "cp docker-compose.yml docker-compose.yml.orig"
  copy:
    src: "{{ tinytinyrss_git_dir }}/docker-compose.yml"
    dest: "{{ tinytinyrss_git_dir }}/docker-compose.yml.orig"
    owner: "{{ tinytinyrss_uuid }}"
    group: "{{ tinytinyrss_guid }}"
  become: true
- name: "overwrite old docker-compose.yml"
  copy:
    src: "docker-compose.yml"
    dest: "{{ tinytinyrss_git_dir }}/docker-compose.yml"
    force: yes
    owner: "{{ tinytinyrss_uuid }}"
    group: "{{ tinytinyrss_guid }}"
  become: true
- name: "replace strings in docker-compose.yml"
  replace:
    path: "{{ tinytinyrss_git_dir }}/docker-compose.yml"
    regexp: "- db:/var/lib/postgresql/data"
    replace: "- {{ tinytinyrss_db_dir }}:/var/lib/postgresql/data"
  become: true
- name: "replace strings in docker-compose.yml"
  replace:
    path: "{{ tinytinyrss_git_dir }}/docker-compose.yml"
    regexp: '- app:/var/www/html:ro'
    replace: "- {{ tinytinyrss_data_dir }}:/var/www/html:ro"
  become: true
- name: "replace strings in docker-compose.yml"
  replace:
    path: "{{ tinytinyrss_git_dir }}/docker-compose.yml"
    regexp: '- app:/var/www/html'
    replace: "- {{ tinytinyrss_data_dir }}:/var/www/html"
  become: true
- name: "docker-compose up -d ."
  docker_compose:
    project_src: "{{ tinytinyrss_git_dir }}"
  environment:
    POSTGRES_USER: "{{ tinytinyrss_postgres_user }}"
    POSTGRES_PASSWORD: "{{ tinytinyrss_postgres_password }}"
    OWNER_UID: "{{ tinytinyrss_uuid }}"
    OWNER_GID: "{{ tinytinyrss_guid }}"
    HTTP_PORT: "{{ tinytinyrss_http_port }}"
    SELF_URL_PATH: "{{ tinytinyrss_http_uri }}"
  become: true
