---
- name: install debian dependencies to compile tarsnap
  ansible.builtin.apt:
    pkg:
    - gcc 
    - libc6-dev 
    - make 
    - libssl-dev 
    - zlib1g-dev 
    - e2fslibs-dev
- name: import source-install.yml tasks
  import_tasks: source-install.yml
