---
- name: check tarsnap executable is present
  ansible.builtin.shell: "which tarsnap"
  register: tarsnap_check
  ignore_errors: true
- name: install tarsnap with pacman
  community.general.pacman:
    name: 
    - tarsnap
  when: tarsnap_check.rc != 0 and ansible_os_family == 'Archlinux'
- name: import debian.yml tasks
  ansible.builtin.import_tasks: debian.yml
  when: tarsnap_check.rc != 0 and ansible_os_family == 'Debian'
#- name: check if /opt/scripts/tarsnap-backup.sh exists
  #ansible.builtin.stat:
    #path: /opt/scripts/tarsnap-backup.sh
  #register: tarsnap_script
#- name: copy tarsnap-backup.sh to /opt/scripts/tarsnap-backup.sh
  #ansible.builtin.template:
  #when: not tarsnap_script.stat.exists
