---
- name: check tarsnap executable is present
  ansible.builtin.shell: "which tarsnap"
  register: tarsnap_check
  ignore_errors: true
- name: install tarsnap with pacman
  community.general.pacman:
    name: 
    - tarsnap
  when: tarsnap_check.rc != 0 and ansible_os_family == 'Archlinux'
- name: import debian.yml tasks
  ansible.builtin.import_tasks: debian.yml
  when: tarsnap_check.rc != 0 and ansible_os_family == 'Debian'
- name: create /opt/scripts directory
  ansible.builtin.file:
    path: /opt/scripts
    state: directory
    owner: root
    group: root
    mode: '0700'
- name: create tarsnap-backup.sh script
  ansible.builtin.template:
    src: tarsnap-backup.sh.j2
    dest: /opt/scripts/tarsnap-backup.sh
    owner: root
    group: root
    mode: '0700'
- name: create cron for /opt/scripts/tarsnap-backup.sh
  ansible.builtin.cron:
    name: tarsnap-backup.sh
    job: "/opt/scripts/tarsnap-backup.sh 2>&1 1>/dev/null"
    weekday: "1"
