---
- name: download tarsnap source code
  ansible.builtin.get_url:
    url: https://www.tarsnap.com/download/tarsnap-autoconf-1.0.39.tgz
    dest: /tmp/tarsnap-autoconf.tgz
- name: unarchive tarsnap source code
  ansible.builtin.unarchive:
    src: '/tmp/tarsnap-autoconf.tgz'
    dest: /tmp/
    remote_src: yes
- name: configure tarsnap source code
  ansible.builtin.shell: ./configure
  args:
    chdir: /tmp/tarsnap-autoconf-1.0.39
- name: build tarsnap from source
  ansible.builtin.shell: make all
  args:
    chdir: /tmp/tarsnap-autoconf-1.0.39
- name: install tarsnap
  ansible.builtin.shell: make install
  args:
    chdir: /tmp/tarsnap-autoconf-1.0.39
- name: clean up /tmp/tarsnap-autoconf-1.0.39
  ansible.builtin.file:
    path: /tmp/tarsnap-autoconf-1.0.39
    state: absent
- name: clean up /tmp/tarsnap-autoconf.tgz
  ansible.builtin.file:
    path: /tmp/tarsnap-autoconf.tgz
    state: absent
