---
bitlbee_root_dir: "/opt/core/bitlbee"
bitlbee_data_dir: "{{ bitlbee_root_dir }}/data"
bitlbee_version: "latest"
bitlbee_uuid: "1000"
bitlbee_guid: "1000"
bitlbee_port: "6667"
bitlbee_ports: 
- "{{ bitlbee_port }}:6667"
bitlbee_volumes:
- /etc/timezone:/etc/timezone:ro
- /etc/localtime:/etc/localtime:ro
- "{{ bitlbee_data_dir }}:/var/lib/bitlbee"
