---
nginx_name: "nextcloud-proxy"
nginx_dir: "{{ nextcloud_root_dir }}/nextcloud-proxy"
nginx_certificate_file: "fullchain.pem"
nginx_key_file: "privkey.pem"
nginx_server_name: "example.com"
nginx_port: 9090
nginx_links:
- nextcloud:nextcloud
nginx_version: "latest"
