---
- name: disable root login
  ansible.builtin.replace:
    path: /etc/ssh/sshd_config
    regexp: 'PermitRootLogin yes'
    replace: 'PermitRootLogin no'
  register: ssh_root_conf
- name: disable password auth
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: "PasswordAuthentication yes"
    state: absent
  register: ssh_pass_enabled
- name: disable password auth
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: "PasswordAuthentication no"
  register: ssh_disable_pass
- name: remove local listen
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: "ListenAddress 127.0.0.1"
    state: absent
  register: ssh_listen_localhost
- name: restart sshd
  ansible.builtin.systemd:
    name: ssh
    state: restarted
  when: (ssh_root_conf.changed or ssh_pass_enabled.changed or ssh_disable_pass.changed or ssh_listen_localhost.changed) and ansible_os_family == 'Debian'
- name: restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
  when: (ssh_root_conf.changed or ssh_pass_enabled.changed or ssh_disable_pass.changed or ssh_listen_localhost.changed) and ansible_os_family != 'Debian'
