---
- name: create cron to keep state in sync
  ansible.builtin.cron:
    name: ansible-pull
    minute: 0
    job: ansible-pull -U https://git.sr.ht/~heywoodlh/ansible playbooks/servers/server.yml 2>&1 1>/dev/null
- name: remove cron for /opt/scripts/sshd-alert.sh
  ansible.builtin.cron:
    name: sshd-alerts
    job: /opt/scripts/sshd-alert.sh 2>&1 1>/dev/null
    state: absent
- name: remove cron for /opt/scripts/sshd-alert.sh
  ansible.builtin.cron:
    name: sshd-alerts
    job: "/opt/scripts/sshd-alert.sh 2>&1 1>/dev/null"
    special_time: reboot
    state: absent
