---
- name: create cron to keep state in sync
  ansible.builtin.cron:
    name: ansible-pull
    minute: 0
    job: ansible-pull -U https://git.sr.ht/~heywoodlh/ansible playbooks/servers/server.yml 2>&1 1>/dev/null
- name: remove zabbix-agent
  community.general.pacman:
    name: "{{ item }}"
    state: absent
  with_items:
  - zabbix-agent
  when: ansible_os_family == 'Archlinux'

