---
- name: check for shadow.conf
  ansible.builtin.stat:
    path: /etc/wireguard/shadow.conf
  register: wireguard_check
- name: update internal ip to new one
  ansible.builtin.replace:
    path: /etc/wireguard/shadow.conf
    regexp: '192.168.1.163'
    replace: '10.0.50.50'
  when: wireguard_check.stat.exists
  register: wireguard_update
- name: bring shadow down and back up
  ansible.builtin.shell: 'wg-quick down shadow && wg-quick up shadow'
  when: wireguard_update.changed
