send_root_dir: "/Users/heywoodlh/send"
container_user: send_docker
container_uid: 501
send_hostname: localhost
self_sign_ssl_options: "/C=US/ST=UT/L=Salt Lake City/O=My Awesome Company/OU=Security/CN={{ send_hostname }}"
