---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for inventory.heywoodlh.io/v1alpha1, Kind: Vultr
  ##
  - apiGroups:
      - inventory.heywoodlh.io
    resources:
      - vultrs
      - vultrs/status
      - vultrs/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for inventory.heywoodlh.io/v1alpha1, Kind: Libvirt
  ##
  - apiGroups:
      - inventory.heywoodlh.io
    resources:
      - libvirts
      - libvirts/status
      - libvirts/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for inventory.heywoodlh.io/v1alpha1, Kind: Server
  ##
  - apiGroups:
      - inventory.heywoodlh.io
    resources:
      - servers
      - servers/status
      - servers/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for inventory.heywoodlh.io/v1alpha1, Kind: Tailscale
  ##
  - apiGroups:
      - inventory.heywoodlh.io
    resources:
      - tailscales
      - tailscales/status
      - tailscales/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
#+kubebuilder:scaffold:rules
