---
nfs_root_dir: "/home/heywoodlh/core/nfs"
nfs_data_dir: "{{ nfs_root_dir }}/data"
nfs_uuid: "1000"
nfs_guid: "1000"
nfs_ports: 
- 111:111
- 111:111/udp
- 2049:2049
- 2049:2049/udp
- 32765:32765
- 32765:32765/udp
- 32767:32767
- 32767:32767/udp
nfs_volumes:
- "{{ nfs_data_dir }}/public:/nfs_share/public"
- "{{ nfs_root_dir }}/exports:/etc/exports:ro" 
- /etc/timezone:/etc/timezone:ro
- /etc/localtime:/etc/localtime:ro
nfs_version: "latest"
