---
- name: "create {{ drone_data_dir }}"
  file:
    path: "{{ drone_data_dir }}"
    state: directory
    force: no
- name: "pull drone:{{ drone_version }} image"
  docker_image:
    name: drone/drone
    tag: "{{ drone_version }}"
    source: pull
- name: run drone container
  docker_container:
    name: drone
    image: "drone/drone:{{ drone_version }}"
    restart_policy: unless-stopped
    volumes: "{{ drone_volumes }}"
    env: "{{ drone_env }}"
