---
- name: delete old generations
  ansible.builtin.command: nix-collect-garbage --delete-older-than 7d
- name: run "nixos-switch" command as heywoodlh
  ansible.builtin.command: /home/heywoodlh/.nix-profile/bin/zsh -c "source /home/heywoodlh/.zshrc && nixos-switch -p ansible"
  become_user: heywoodlh
