---
second_version: "latest"
second_uri: "http://second:3000"
second_image: "heywoodlh/second"
second_uuid: "1000"
second_guid: "1000"
second_env:
  TZ: "America/Denver"
  WEBSITE_ORIGIN: "{{ second_uri }}"
