---
- name: "create {{ statping_root_dir }}"
  file:
    path: "{{ statping_root_dir }}"
    state: directory
    force: no
- name: "pull {{ statping_image }}:{{ statping_version }} image"
  community.docker.docker_image:
    name: "{{ statping_image }}"
    tag: "{{ statping_version }}"
    source: pull
- name: run statping container
  community.docker.docker_container:
    name: statping
    image: "{{ statping_image }}:{{ statping_version }}"
    restart_policy: unless-stopped
    volumes: "{{ statping_volumes }}"
    links:
    - statping-db:db
    env:
      DB_CONN: "postgres"
      DB_HOST: "db"
      DB_USER: "{{ postgres_user }}"
      DB_PASS: "{{ postgres_password }}"
      DB_PORT: "5432"
      DB_DATABASE: "{{ postgres_db }}"
      ADMIN_USER: "{{ statping_admin_username }}" 
      ADMIN_PASSWORD: "{{ statping_admin_password }}"
