---
- name: install arch packages
  community.general.pacman:
    name: "{{ item }}"
    update_cache: yes
  with_items:
  - cronie
  - git
  - curl
  - ruby
  - sudo
  - ufw
  - vim
  when: ansible_os_family == 'Archlinux' 
- name: install debian packages
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
  - git
  - curl
  - ruby
  - sudo
  - sudo
  - ufw
  - vim
  when: ansible_os_family == 'Debian' 
- name: enable cronie service
  ansible.builtin.systemd:
    name: cronie.service
    enabled: yes
    state: started
  when: ansible_os_family == 'Archlinux'
