---
- name: install arch packages
  community.general.pacman:
    name: "{{ item }}"
    update_cache: yes
  with_items:
  - cronie
  - git
  - curl
  - python-pip
  - nix
  - sudo
  - ufw
  - vim
  - zsh
  when: ansible_os_family == 'Archlinux' 
- name: start nix-daemon
  ansible.builtin.systemd:
    name: nix-daemon.service
    start: started
    enabled: true
  when: ansible_os_family == 'Archlinux' 
- name: install debian packages
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
  - git
  - curl
  - python3-pip
  - sudo
  - ufw
  - vim
  - zsh
  when: ansible_os_family == 'Debian' 
- name: enable cronie service
  ansible.builtin.systemd:
    name: cronie.service
    enabled: yes
    state: started
  when: ansible_os_family == 'Archlinux'
