---
- name: check if nix is installed
  shell: command -v nix >/dev/null 2>&1
  register: nix_installed
  ignore_errors: yes
- name: install nix with determinate systems installer
  ansible.builtin.command: "curl -sSf -L https://install.determinate.systems/nix | sh -s -- install --no-confirm"
  when: nix_installed.rc not in [ 0 ]
