---
- name: arch linux mirrorlist repo configuration
  ansible.builtin.copy:
    src: mirrorlist
    dest: /etc/pacman.d/mirrorlist
    backup: true
    owner: root
    mode: 644
  when: ansible_distribution == 'Archlinux' and ansible_architecture == 'x86_64'
- name: arch linux arm mirrorlist repo configuration
  ansible.builtin.copy:
    src: mirrorlist-alarm
    dest: /etc/pacman.d/mirrorlist
    backup: true
    owner: root
    mode: 644
  when: ansible_distribution == 'Archlinux' and ansible_architecture != 'x86_64' 
