---
- name: install firefox ppa
  ansible.builtin.apt_repository:
    repo: ppa:mozillateam/ppa
- name: disable firefox installation with snap
  ansible.builtin.copy:
    src: apt/mozilla-firefox
    dest: /etc/apt/preferences.d/mozilla-firefox
- name: remove firefox snap
  community.general.snap:
    name: firefox
    state: absent
- name: install firefox with ppa
  ansible.builtin.apt:
    name: firefox
    update_cache: yes
- name: disable automatic updates
  ansible.builtin.copy:
    src: apt/20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
