---
- name: "create {{ statping_root_dir }}"
  file:
    path: "{{ statping_root_dir }}"
    state: directory
    force: no
- name: create statping volume
  docker_volume:
    name: statping 
- name: "pull statping:{{ statping_version }} image"
  docker_image:
    name: hunterlong/statping
    tag: "{{ statping_version }}"
    source: pull
- name: run statping container
  docker_container:
    name: statping
    image: "hunterlong/statping:{{ statping_version }}"
    restart_policy: unless-stopped
    volumes: "{{ statping_volumes }}"
    links:
    - statping-db:db
