---
- name: create heywoodlh
  ansible.builtin.user:
    name: heywoodlh
    shell: /bin/bash
- name: passwordless sudo for heywoodlh
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/heywoodlh
    state: present
    create: yes
    regexp: "^heywoodlh"
    line: "heywoodlh ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
- name: remove sudo configuration from archinstall script if exists
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: absent
    regexp: "^heywoodlh"
    line: "heywoodlh ALL=(ALL) ALL"
    validate: 'visudo -cf %s'
- name: create heywoodlh .ssh directory
  ansible.builtin.file:
    path: /home/heywoodlh/.ssh
    mode: '0700'
    owner: heywoodlh
    state: directory
- name: grab authorized_keys file
  ansible.builtin.copy:
    src: authorized_keys
    dest: /home/heywoodlh/.ssh/authorized_keys
    mode: '0600'
    owner: heywoodlh
- name: add heywoodlh to docker group
  ansible.builtin.user:
    name: heywoodlh
    group: docker
    append: yes
- name: install user packages
  community.general.pacman:
    name: "{{ item }}"
    update_cache: yes
  with_items:
  - "vim"
  - "git"
  - "python-pip"
  - "curl"
  - "mosh"
  when: ansible_os_family == 'Archlinux'
- name: install user packages
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
  - "vim"
  - "git"
  - "curl"
  - "python3-pip"
  - "mosh"
  when: ansible_os_family == 'Debian'
- name: download dotfiles
  ansible.builtin.git:
    repo: 'https://git.sr.ht/~heywoodlh/conf'
    dest: '/home/heywoodlh/opt/conf'
  become: yes
  become_user: heywoodlh
- name: install dotfiles
  ansible.builtin.command: "/home/heywoodlh/opt/conf/setup.sh"
  become: yes
  become_user: "heywoodlh"
  args:
    chdir: /home/heywoodlh/opt/conf
- name: make sure bash_profile is sourced by .bashrc
  ansible.builtin.lineinfile:
    path: /home/heywoodlh/.bashrc
    create: yes
    line: "source ~/.bash_profile"
  become: yes
  become_user: "heywoodlh"
