---
- name: "create bitlbee directories in {{ bitlbee_root_dir }}"
  file:
    path: "{{ item }}"
    state: directory
    force: no
    owner: "{{ bitlbee_uuid }}"
    group: "{{ bitlbee_guid }}"
    recurse: yes
  with_items:
  - "{{ bitlbee_root_dir }}"
  - "{{ bitlbee_data_dir }}"
  become: true
- name: "pull ezkrg/bitlbee-libpurple:{{ bitlbee_version }} image"
  docker_image:
    name: ezkrg/bitlbee-libpurple
    tag: "{{ bitlbee_version }}"
    source: pull
  become: true
- name: run bitlbee container
  docker_container:
    name: bitlbee
    image: "ezkrg/bitlbee-libpurple:{{ bitlbee_version }}"
    user: "{{ bitlbee_uuid }}"
    restart_policy: unless-stopped
    volumes: "{{ bitlbee_volumes }}"
    ports: "{{ bitlbee_ports }}"
  become: true
