---
- name: Delete old generations
  ansible.builtin.command: nix-collect-garbage --delete-older-than 7d

- name: Run git clone https://github.com/heywoodlh/nixos-configs
  ansible.builtin.git:
    repo: https://github.com/heywoodlh/nixos-configs
    dest: /tmp/nixos-configs
    force: true

- name: Run nixos-rebuild against hostname
  ansible.builtin.shell: "nixos-rebuild switch --flake /tmp/nixos-configs#$(hostname) --impure"

- name: Remove /tmp/nixos-configs
  ansible.builtin.file:
    path: /tmp/nixos-configs
    state: absent
    recurse: true
