---
- name: Install lsb_release
  ansible.builtin.apt:
    name: lsb-release
    install_recommends: no
    update_cache: yes
    cache_valid_time: 3600

- name: Disable Enterprise repository
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/pve-enterprise.list
    state: absent

- name: Get distribution codename
  ansible.builtin.shell: lsb_release -c | cut -f 2
  register: codename

- ansible.builtin.set_fact:
    codename: "{{ codename.stdout }}"

- name: Add no-subscription repository
  template:
    src: templates/pve-no-subscription.list.j2
    dest: /etc/apt/sources.list.d/pve-no-subscription.list

- name: Disable subscription notice
  ansible.builtin.replace:
      path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
      regexp: "res === null \\|\\| res === undefined \\|\\| \\!res \\|\\| res\\n\\t\\t\\t.data.status.toLowerCase\\(\\) \\!== 'active'"
      replace: "false"
      backup: yes

- name: Restart proxmox web interface
  ansible.builtin.systemd_service:
    name: pveproxy.service
    state: restarted
