---
- name: Configure root user
  block:
    - name: Create root .ssh directory
      ansible.builtin.file:
        path: /root/.ssh
        mode: '0700'
        owner: root
        state: directory

    - name: Update authorized_keys file
      ansible.builtin.copy:
        src: users/root/authorized_keys
        dest: /root/.ssh/authorized_keys
        mode: '0600'
        owner: root

- name: Configure heywoodlh user
  block:
    - name: Create heywoodlh
      ansible.builtin.user:
        name: heywoodlh

    - name: Passwordless sudo for heywoodlh
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/heywoodlh
        state: present
        create: true
        regexp: "^heywoodlh"
        line: "heywoodlh ALL=(ALL) NOPASSWD: ALL"
        validate: 'visudo -cf %s'

    - name: Remove sudo configuration from archinstall script if exists
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: absent
        regexp: "^heywoodlh"
        line: "heywoodlh ALL=(ALL) ALL"
        validate: 'visudo -cf %s'

    - name: Create heywoodlh .ssh directory
      ansible.builtin.file:
        path: /home/heywoodlh/.ssh
        mode: '0700'
        owner: heywoodlh
        state: directory

    - name: Grab authorized_keys file
      ansible.builtin.get_url:
        url: https://github.com/heywoodlh.keys
        dest: /home/heywoodlh/.ssh/authorized_keys
        mode: '0600'
        owner: heywoodlh

    - name: Install nix
      ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf -L https://install.determinate.systems/nix/tags/v0.10.0 | sh -s -- install --no-confirm
      become_user: heywoodlh
      args:
        executable: /bin/bash

    - name: Install Home-Manager config
      ansible.builtin.shell: "/nix/var/nix/profiles/default/bin/nix --extra-experimental-features 'nix-command flakes' run github:heywoodlh/nixos-configs#homeConfigurations.heywoodlh-server.activationPackage --impure"
      become_user: heywoodlh
      become: true
      args:
        executable: /bin/bash

    - name: Check if /home/heywoodlh/.nix-profile/bin/fish exists
      ansible.builtin.stat:
        path: "/home/heywoodlh/.nix-profile/bin/fish"
      register: fish_check

    - name: Add /home/heywoodlh/.nix-profile/bin/fish to /etc/shells
      ansible.builtin.lineinfile:
        path: /etc/shells
        line: "/home/heywoodlh/.nix-profile/bin/fish"
      when: fish_check.stat.exists

    - name: Set heywoodlh's shell to /home/heywoodlh/.nix-profile/bin/fish
      ansible.builtin.user:
        name: heywoodlh
        shell: /home/heywoodlh/.nix-profile/bin/fish
      when: fish_check.stat.exists

