---
- name: Configure root user
  block:
    - name: Create root .ssh directory
      ansible.builtin.file:
        path: /root/.ssh
        mode: '0700'
        owner: root
        state: directory

    - name: Update authorized_keys file
      ansible.builtin.copy:
        src: users/root/authorized_keys
        dest: /root/.ssh/authorized_keys
        mode: '0600'
        owner: root

- name: Configure heywoodlh user
  block:
    - name: Create heywoodlh
      ansible.builtin.user:
        name: heywoodlh

    - name: Passwordless sudo for heywoodlh
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/heywoodlh
        state: present
        create: true
        regexp: "^heywoodlh"
        line: "heywoodlh ALL=(ALL) NOPASSWD: ALL"
        validate: 'visudo -cf %s'

    - name: Remove sudo configuration from archinstall script if exists
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: absent
        regexp: "^heywoodlh"
        line: "heywoodlh ALL=(ALL) ALL"
        validate: 'visudo -cf %s'

    - name: Create heywoodlh .ssh directory
      ansible.builtin.file:
        path: /home/heywoodlh/.ssh
        mode: '0700'
        owner: heywoodlh
        state: directory

    - name: Grab authorized_keys file
      ansible.builtin.copy:
        src: users/heywoodlh/authorized_keys
        dest: /home/heywoodlh/.ssh/authorized_keys
        mode: '0600'
        owner: heywoodlh

    - name: Check if nix installed
      ansible.builtin.stat:
        path: /home/heywoodlh/.nix-profile/bin/nix
      register: nix_check

    - name: Install nix in single-user mode
      ansible.builtin.shell: curl -L https://nixos.org/nix/install | sh -s -- --no-daemon --yes
      become_user: heywoodlh
      when: nix_check.stat.exists == false

    - name: Install my nixos-configs server flake
      ansible.builtin.command: "/home/heywoodlh/.nix-profile/bin/nix --extra-experimental-features 'nix-command flakes' run github:heywoodlh/nixos-configs#homeConfigurations.heywoodlh-server.activationPackage --impure"
      become: true
      become_user: heywoodlh

    - name: Add /home/heywoodlh/.nix-profile/bin/zsh to /etc/shells
      ansible.builtin.lineinfile:
        path: /etc/shells
        line: "/home/heywoodlh/.nix-profile/bin/zsh"

    - name: Set heywoodlh's shell to /home/heywoodlh/.nix-profile/bin/zsh
      ansible.builtin.user:
        name: heywoodlh
        shell: /home/heywoodlh/.nix-profile/bin/zsh

    - name: Create /home/heywoodlh/.zsh.d
      ansible.builtin.file:
        path: /home/heywoodlh/.zsh.d
        state: directory
        mode: '0700'
        owner: heywoodlh

    - name: Add ansible-switch alias to /home/heywoodlh/.zsh.d/custom
      ansible.builtin.lineinfile:
        path: /home/heywoodlh/.zsh.d/custom
        line: "alias ansible-switch='sudo ansible-pull -c=local -U https://github.com/heywoodlh/ansible setup.yml; sudo ansible-pull -c=local -U https://github.com/heywoodlh/ansible playbooks/servers/server.yml'"
        create: true
        owner: heywoodlh
