---
- name: Configure root user
  block:
    - name: Create root .ssh directory
      ansible.builtin.file:
        path: /root/.ssh
        mode: '0700'
        owner: root
        state: directory

    - name: Update authorized_keys file
      ansible.builtin.copy:
        src: users/root/authorized_keys
        dest: /root/.ssh/authorized_keys
        mode: '0600'
        owner: root

- name: Configure heywoodlh user
  block:
    - name: Create heywoodlh
      ansible.builtin.user:
        name: heywoodlh
        shell: /bin/bash

    - name: Create /etc/sudoers.d
      ansible.builtin.file:
        path: /etc/sudoers.d/
        state: directory

    - name: Passwordless sudo for heywoodlh
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/heywoodlh
        state: present
        create: true
        regexp: "^heywoodlh"
        line: "heywoodlh ALL=(ALL) NOPASSWD: ALL"
        validate: 'visudo -cf %s'

    - name: Remove sudo configuration from archinstall script if exists
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: absent
        regexp: "^heywoodlh"
        line: "heywoodlh ALL=(ALL) ALL"
        validate: 'visudo -cf %s'

    - name: Create heywoodlh .ssh directory
      ansible.builtin.file:
        path: /home/heywoodlh/.ssh
        mode: '0700'
        owner: heywoodlh
        state: directory

    - name: Grab authorized_keys file
      ansible.builtin.get_url:
        url: https://github.com/heywoodlh.keys
        dest: /home/heywoodlh/.ssh/authorized_keys
        mode: '0600'
        owner: heywoodlh

    - name: Install flakes
      include_tasks: ./include/flakes.yml
      loop:
      - tmux
      - vim
      - git

    - name: Check if /home/heywoodlh/.nix-profile/bin/tmux exists
      ansible.builtin.stat:
        path: "/home/heywoodlh/.nix-profile/bin/tmux"
      register: tmux_check

    - name: Add /home/heywoodlh/.nix-profile/bin/tmux to /etc/shells
      ansible.builtin.lineinfile:
        path: /home/heywoodlh/.bashrc
        create: true
        line: "[ -z ${TMUX} ] && { /home/heywoodlh/.nix-profile/bin/tmux attach || exec /home/heywoodlh/.nix-profile/bin/tmux new-session && exit;}"
        owner: heywoodlh
      when: tmux_check.stat.exists

    - name: Add ansible-switch alias to /home/heywoodlh/.config/fish/config.fish
      ansible.builtin.lineinfile:
        path: /home/heywoodlh/.config/fish/config.fish
        create: true
        owner: heywoodlh
        line: alias ansible-switch "sudo ansible-pull -c=local -U https://github.com/heywoodlh/ansible setup.yml; sudo ansible-pull -c=local -U https://github.com/heywoodlh/ansible operator/roles/server/standalone.yml"
      when: tmux_check.stat.exists
      become_user: heywoodlh
      become: true
