---
- name: enable nfs kernel modules on host
  modprobe:
    name: "{{ item }}"
    state: present
  with_items:
  - "nfs"
  - "nfsd"
  - "rpcsec_gss_krb5"
  become: true
- name: "create {{ nfs_root_dir }}"
  file:
    path: "{{ nfs_root_dir }}"
    state: directory
    force: no
- name: "create {{ nfs_data_dir }}"
  file:
    path: "{{ nfs_data_dir }}"
    state: directory
- name: "pull erichough/nfs-server:{{ nfs_version }} image"
  docker_image:
    name: erichough/nfs-server
    tag: "{{ nfs_version }}"
    source: pull
- name: run nfs container
  docker_container:
    name: nfs
    image: "erichough/nfs-server:{{ nfs_version }}"
    restart_policy: unless-stopped
    volumes: "{{ nfs_volumes }}"
    ports:
    - "{{ nfs_port }}:2049"
    capabilities:
    - SYS_ADMIN
