---
- name: create send-docker redis directory
  file:
    path: /opt/{{ redis_container_name }}
    mode: 0700
    owner: "{{ container_uid }}"
    state: directory
  become: true
- name: deploy redis docker container
  docker_container:
    name: "{{ redis_container_name }}"
    image: redis
    restart_policy: unless-stopped
    user: "{{ container_uid }}"
    volumes:
    - /opt/{{ redis_container_name }}:/data
  become: true
