---
- name: install arch packages
  community.general.pacman:
    name: "{{ item }}"
  with_items:
  - cronie
  - sudo
  - ufw
  - neofetch
  when: ansible_os_family == 'Archlinux' 
- name: install debian packages
  ansible.builtin.apt:
    name: "{{ item }}"
  with_items:
  - sudo
  - cron
  - ufw
  - neofetch
  when: ansible_os_family == 'Debian' 
- name: enable cronie service
  ansible.builtin.systemd:
    name: cronie.service
    enabled: yes
    state: started
  when: ansible_os_family == 'Archlinux' 
