---
- name: download powershell repo package
  ansible.builtin.get_url:
    url: "https://packages.microsoft.com/config/ubuntu/{{ ansible_distribution_major_version }}.04/packages-microsoft-prod.deb"
    dest: /tmp/packages-microsoft-prod.deb
    force_basic_auth: yes
- name: install microsoft powershell repo
  ansible.builtin.apt:
    deb: /tmp/packages-microsoft-prod.deb
    update_cache: yes
- name: install latest version of powershell
  ansible.builtin.apt:
    name: powershell
    update_cache: yes
