---
postgres_name: "rundeck-db"
postgres_version: "latest"
postgres_db_dir: "{{ rundeck_root_dir }}/rundeck-db"
postgres_user: "rundeck"
postgres_db: "{{ postgres_user }}"
postgres_password: "changeme"
