---
- name: create cron to keep state in sync
  ansible.builtin.cron:
    name: ansible-pull
    minute: 0
    job: ansible-pull -U https://git.sr.ht/~heywoodlh/ansible playbooks/red-team/red-team.yml 2>&1 1>/dev/null

