---
- name: install pip3
  package:
    name: python3-pip
    state: latest
  become: true
- name: install pip packages
  pip:
    name: "{{ item }}"
  with_items: "{{ pip_packages }}"
  when: "{{ pip_packages }} != '' }}"
- name: install pip packages globally
  pip:
    name: "{{ item }}"
  become: true
  with_items: "{{ global_pip_packages }}"
  when: "{{ global_pip_packages != '' }}"
