---
synapse_root_dir: "/opt/core/synapse"
synapse_data_dir: "{{ synapse_root_dir }}/data"
synapse_server_name: "localhost"
synapse_report_stats: "no"
synapse_dirs:
- "{{ synapse_root_dir }}"
- "{{ synapse_data_dir }}"
synapse_version: "latest"
synapse_image: "avhost/docker-matrix"
synapse_uuid: "991"
synapse_guid: "991"
synapse_ports:
  8448:8448
  8008:8008
  3478:3478
synapse_env:
  TZ: "America/Denver"
  SERVER_NAME: "{{ synapse_server_name }}"
  REPORT_STATS: "no"
synapse_volumes:
- "{{ synapse_data_dir }}:/data"
