- name: allow ssh 
  community.general.ufw:
    rule: allow
    port: ssh
    proto: tcp
- name: allow mosh 
  community.general.ufw:
    rule: allow
    port: 60000:61000
    proto: udp
- name: get ufw service status 
  ansible.builtin.systemd:
    name: "ufw"
    state: started
    enabled: yes
