- name: allow ssh 
  community.general.ufw:
    rule: allow
    port: ssh
    proto: tcp
- name: allow mosh 
  community.general.ufw:
    rule: allow
    port: 60000:61000
    proto: udp
- name: allow port 5000 (reverse shells) 
  community.general.ufw:
    rule: allow
    port: 5000 
    proto: tcp
- name: allow port 4444 (default metasploit lport)
  community.general.ufw:
    rule: allow
    port: 4444
    proto: tcp
- name: allow beef ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
  - "6789"
  - "61985"
  - "61986"
  #- "3000" ## Don't allow 3000 -- access it via localhost
- name: enable and start ufw systemd service
  ansible.builtin.systemd:
    name: "ufw"
    state: started
    enabled: yes
- name: enable ufw
  community.general.ufw:
    state: enabled
