---
- name: "create ferdi directories in {{ ferdi_root_dir }}"
  file:
    path: "{{ item }}"
    state: directory
    force: no
    owner: "{{ ferdi_uuid }}"
    group: "{{ ferdi_guid }}"
    recurse: yes
  with_items:
  - "{{ ferdi_root_dir }}"
  - "{{ ferdi_data_dir }}"
  - "{{ ferdi_config_dir }}"
  - "{{ ferdi_recipe_dir }}"
  become: true
- name: "pull getferdi/ferdi-server:{{ ferdi_version }} image"
  docker_image:
    name: getferdi/ferdi-server
    tag: "{{ ferdi_version }}"
    source: pull
  become: true
- name: run ferdi container
  docker_container:
    name: ferdi
    image: "getferdi/ferdi-server:{{ ferdi_version }}"
    restart_policy: unless-stopped
    volumes: "{{ ferdi_volumes }}"
    ports: "{{ ferdi_ports }}"
  become: true
