---
collections:
  - name: cloud.common
    version: "2.1.1"
  - name: community.docker
    version: "3.4.0"
  - name: community.general
    version: "6.3.0"
  - name: community.kubernetes
    version: "2.0.1"
  - name: community.libvirt
    version: "1.2.0"
  - name: kubernetes.core
    version: "2.4.0"
  - name: operator_sdk.util
    version: "0.4.0"
  - name: vultr.cloud
    version: "1.7.0"
