---
- name: set http/https_proxy
  ansible.builtin.lineinfile:
    path: /etc/environment
    line: "{{ item }}"
    mode: 755
    owner: root
    create: yes
  with_items:
  - http_proxy=http://10.50.50.1:3128
  - https_proxy=$http_proxy
  - no_proxy="'localhost,127.0.0.1'"