---
- name: disable password auth
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: "PasswordAuthentication no"
  register: ssh_conf
- name: restart sshd
  ansible.builtin.systemd:
    name: ssh
    state: restarted
  when: ssh_conf.changed and ansible_os_family == 'Debian'
- name: restart sshd
  ansible.builtin.systemd:
    name: sshd
    state: restarted
  when: ssh_conf.changed and ansible_os_family != 'Debian'
